#pragma once

#include <cstddef>
#include <cstdint>

enum PM_STATUS {
  PM_STATUS_SUCCESS = 0,
  PM_STATUS_ALREADY_TRACKING_PROCESS = 7,
};
enum PM_METRIC {
  PM_METRIC_DISPLAYED_FPS = 11,
  PM_METRIC_PRESENTED_FPS = 12,
  PM_METRIC_GPU_POWER = 27,
  PM_METRIC_GPU_FREQUENCY = 29,
  PM_METRIC_GPU_TEMPERATURE = 30,
  PM_METRIC_GPU_FAN_SPEED = 31,
  PM_METRIC_GPU_UTILIZATION = 32,
  PM_METRIC_GPU_MEM_USED = 46,
  PM_METRIC_CPU_UTILIZATION = 56,
  PM_METRIC_CPU_POWER = 58,
  PM_METRIC_CPU_TEMPERATURE = 59,
  PM_METRIC_CPU_FREQUENCY = 60,
  PM_METRIC_GPU_CARD_POWER = 76,
};
enum PM_STAT {
  PM_STAT_NONE = 0,
  PM_STAT_AVG = 1,
  PM_STAT_PERCENTILE_01 = 5,
};
enum PM_DEVICE_TYPE {
  PM_DEVICE_TYPE_INDEPENDENT = 0,
  PM_DEVICE_TYPE_GRAPHICS_ADAPTER = 1,
  PM_DEVICE_TYPE_SYSTEM = 2,
};
enum PM_DEVICE_VENDOR {
  PM_DEVICE_VENDOR_INTEL,
  PM_DEVICE_VENDOR_NVIDIA,
  PM_DEVICE_VENDOR_AMD,
  PM_DEVICE_VENDOR_UNKNOWN,
};
enum PM_METRIC_AVAILABILITY {
  PM_METRIC_AVAILABILITY_AVAILABLE = 0,
  PM_METRIC_AVAILABILITY_UNAVAILABLE = 1,
};
struct PM_INTROSPECTION_STRING { const char *pData; };
struct PM_INTROSPECTION_OBJARRAY { const void **pData; size_t size; };
struct PM_INTROSPECTION_DEVICE_LUID { const uint8_t *pData; uint32_t size; };
struct PM_INTROSPECTION_DEVICE {
  uint32_t id;
  PM_DEVICE_TYPE type;
  PM_DEVICE_VENDOR vendor;
  PM_INTROSPECTION_STRING *pName;
  PM_INTROSPECTION_DEVICE_LUID *pLuid;
};
struct PM_INTROSPECTION_DEVICE_METRIC_INFO {
  uint32_t deviceId;
  PM_METRIC_AVAILABILITY availability;
  uint32_t arraySize;
};
struct PM_INTROSPECTION_METRIC {
  PM_METRIC id;
  int type;
  int unit;
  int preferredUnitHint;
  void *pTypeInfo;
  PM_INTROSPECTION_OBJARRAY *pStatInfo;
  PM_INTROSPECTION_OBJARRAY *pDeviceMetricInfo;
};
struct PM_INTROSPECTION_ROOT {
  PM_INTROSPECTION_OBJARRAY *pMetrics;
  PM_INTROSPECTION_OBJARRAY *pEnums;
  PM_INTROSPECTION_OBJARRAY *pDevices;
  PM_INTROSPECTION_OBJARRAY *pUnits;
};
struct PM_QUERY_ELEMENT {
  PM_METRIC metric;
  PM_STAT stat;
  uint32_t deviceId;
  uint32_t arrayIndex;
  uint64_t dataOffset;
  uint64_t dataSize;
};
struct PM_SESSION;
struct PM_DYNAMIC_QUERY;
using PM_SESSION_HANDLE = PM_SESSION *;
using PM_DYNAMIC_QUERY_HANDLE = PM_DYNAMIC_QUERY *;
