APPVER = 1.8.0

NAME = pcmonitor

CFLAGS += -I../../common/pcmonitor

OBJS += main.o
OBJS += monitor.o
OBJS += renderer.o
OBJS += ../../common/pcmonitor/protocol.o
OBJS += ../vendor/trezor-crypto/memzero.o
OBJS += ../timer.o
OBJS += ../firmware/startup.o
OBJS += ../firmware/header.o

include ../Makefile.include
